application: babushka-example
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: yaml
  version: latest

handlers:
- url: .*
  script: example.main.app
